# Generated by Django 5.1.7 on 2025-12-03 03:13

import fileshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileshare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharefile",
            name="share_key",
            field=models.CharField(
                default=fileshare.models.generate_share_key,
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
