# Generated by Django 6.0.2 on 2026-09-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileshare", "0002_alter_sharefile_share_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharefile",
            name="file",
            field=models.FileField(upload_to="media/sharefiles/"),
        ),
    ]
