# Generated by Django 5.1.7 on 2026-09-30 04:44

import django.core.validators
import dropfeed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="file_extension",
            field=models.CharField(default="mp3", editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name="recording",
            name="audio_file",
            field=models.FileField(
                upload_to=dropfeed.models.recording_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "m4a",
                            "aac",
                            "ogg",
                            "opus",
                            "flac",
                            "wav",
                        ]
                    )
                ],
            ),
        ),
    ]
